### PR TITLE
Rework zend_mm_free_heap heap corruption reporting to provide timesta…

### PR DESCRIPTION
**Pull request by StevenLevine**
…mp, pid, tid and reason details.

### CODE REVIEW

**Comment by StevenLevine** [comment]
The code looks right to my eyes, but I should probably test under the debugger before Massimo gets access to the build.

**Comment by psmedley** [comment]
https://smedley.id.au/tmp/php-7.4.28-os2-debug-20220606.zip

**Comment by StevenLevine** [comment]
That was as fast merge and rebuild and test too. :-)  It's ready to go to Massimo.

**Comment by psmedley** [comment]
Ok will post it later. Your PR timing worked in perfectly with work from home and a lunch break.

**Pull request merged**
