### PR TITLE
Avoid exception in persistent_stream_open_function if we get here wit…

### PR DESCRIPTION
**Pull request by StevenLevine**
…h a NULL globals pointer.

Just fail.

### CODE REVIEW

**Comment by psmedley** [comment]
This fix is included in https://smedley.id.au/tmp/php-7.4.32-os2-debug-20230214.zip

**Comment by StevenLevine** [comment]
>https://smedley.id.au/tmp/php-7.4.32-os2-debug-20230214.zip

I'm getting traps on startup on this build testing with

  php -c. --version

Is this build working for others?

**Comment by psmedley** [comment]
I'll check later today, I didn't get an opportunity to test locally.

**Comment by StevenLevine** [comment]
>https://smedley.id.au/tmp/php-7.4.32-os2-debug-20230214.zip

Red herring.  It looked like I had enough memory, but I didn't.  After
shutting down a couple of browser instances, we are back to a working php.

**Pull request merged**
